### ISSUE TITLE
Can not edit nullable field uuid(string) foreign key

### ISSUE THREAD

**Issue by ydhn** [SoftwareBrothers/adminjs-prisma#11]
Hi. I'm using this package with my postgres database and most of the primary keys are managed by UUID in my case.  
https://github.com/SoftwareBrothers/adminjs-prisma/blob/8d749a1493544cef59822eecca3fda00893f0034/src/utils/converters.ts#L24
So the problem is that if the foreign key is nullable uuid, I cannot edit the record which containing null foreign key because of that line forces null to be string "null". and it causes the database error like:
```
Invalid `prisma.someEntity.update()` invocation:

  Inconsistent column data: Error creating UUID, invalid length: expected one of [36, 32], found 4

```
cause it tries to update the foreign key not null, but `"null"`.  
  
I think many Prisma user might use uuid as their usual primary key type, and foreign key being nullable is a very usual case.. I hope this can be fixed quickly.

**Comment by NotAmaan** [comment]
Getting an error on update as well, using NestJS, Prisma and adminjs

**Comment by ydhn** [comment]
> Getting an error on update as well, using NestJS, Prisma and adminjs

Can you show me the error from prisma client?

**Comment by ydhn** [comment]
> Getting an error on update as well, using NestJS, Prisma and adminjs

@NotAmaan Can you show me the error from prisma client?
