### ISSUE TITLE
Repo actively maintained?

### ISSUE THREAD

**Issue by goldylucks** [SoftwareBrothers/adminjs-prisma#26]
Thanks for the awesome project 💪

I'm using it with a mongoose project and it works great.

I'm considering adminJS for another Prisma project. Is this repo maintained? I see issues from months ago w/o responses, and last delpoyment from July.

Thanks :)

**Comment by krzysztofstudniarek** [comment]
Hey @goldylucks,

**Comment by goldylucks** [comment]
Perfect! 💕
