### ISSUE TITLE
Package breaks with prisma version >= 4.14.0 (_baseDmmf is removed)

### ISSUE THREAD

**Issue by Yureien** [SoftwareBrothers/adminjs-prisma#35]
`prisma._baseDmmf` was removed with this commit: https://github.com/prisma/prisma/commit/42087bfb0148b87d9b927417242b73ce170ad8bd

Right now, we are using a really hacky method to get the DMMF. It can be simply obtained using `Prisma.dmmf`.

Here is my diff on how I patched it (not sure if passing the `enumMaps` through the constructor is the right way or if we can use some other way):

```diff
diff --git a/node_modules/@adminjs/prisma/lib/Resource.js b/node_modules/@adminjs/prisma/lib/Resource.js
index 7bcc180..7c65c06 100644
--- a/node_modules/@adminjs/prisma/lib/Resource.js
+++ b/node_modules/@adminjs/prisma/lib/Resource.js
@@ -13,10 +13,10 @@ export class Resource extends BaseResource {
     propertiesObject;
     constructor(args) {
         super(args);
-        const { model, client } = args;
+        const { model, client, enumMap } = args;
         this.model = model;
         this.client = client;
-        this.enums = this.client._baseDmmf.datamodelEnumMap;
+        this.enums = enumMap;
         this.manager = this.client[lowerCase(model.name)];
         this.propertiesObject = this.prepareProperties();
     }
```

To get the DMMF properly (and not using internal parameters), we can do it this way:

```js
import { Prisma } from '@prisma/client';

const prisma = new Prisma.client();

const datamodel = Prisma.dmmf.datamodel;
const models = datamodel.models.reduce((acc, model) => ((acc[model.name] = model), acc), {});
const enumMap = datamodel.enums.reduce((acc, enumItem) => ((acc[enumItem.name] = enumItem), acc), {});

const resources = [
  {
    resource: { model: models['ModelName'], client: prisma, enumMap: enumMap },
    ...
```

I would create a PR for the `enumMaps` fix if my patch is acceptable, otherwise, please let me know the best way. I would also update the "hacky" way of using `_baseDmmf` to use the official dmmf parameter but I am not sure where all it is getting referenced. Could you please let me know the docs/examples where we are using it?

**Comment by MichaelTao** [comment]
@Yureien Running into the same issue. I tried your fix but it didn't work for me. Can you share your code as reference?

**Comment by Yureien** [comment]
> @Yureien Running into the same issue. I tried your fix but it didn't work for me. Can you share your code as reference?

That is my code. You need to apply the patch via `patch-package` or manually. After that, here is how you should use it:

```
import { Prisma } from '@prisma/client';
import * as AdminJSPrisma from '@adminjs/prisma'

AdminJS.registerAdapter({
  Resource: AdminJSPrisma.Resource,
  Database: AdminJSPrisma.Database,
})

const prisma = new Prisma.client();

const datamodel = Prisma.dmmf.datamodel;
const models = datamodel.models.reduce((acc, model) => ((acc[model.name] = model), acc), {});
const enumMap = datamodel.enums.reduce((acc, enumItem) => ((acc[enumItem.name] = enumItem), acc), {});

const adminOptions = {
  // We pass Publisher to `resources`
  resources: [{
    resource: { model: models['ModelName'], client: prisma, enumMap: enumMap },
    options: {},
  }],
};

const admin = new AdminJS(adminOptions);

... rest of code
```

Remember to update your model's name in `ModelName`.

If you are still facing any issues, please send your error message.

**Comment by MichaelTao** [comment]
@Yureien thanks for sharing. Where do you get the patch-package?

**Comment by Yureien** [comment]
> @Yureien thanks for sharing. Where do you get the patch-package?

Follow any online guide on how to use it. For example, https://javascript.plainenglish.io/live-npm-package-patching-with-patch-package-b8f30d47779c

BTW, AdminJS was also broken for me on 7.0.4. I am using the following versions:

[@adminjs/fastify](https://npmjs.com/package/@adminjs/fastify): [^4.0.0](https://npmjs.com/package/@adminjs/fastify),
[@adminjs/prisma](https://npmjs.com/package/@adminjs/prisma): [^4.0.0](https://npmjs.com/package/@adminjs/prisma),
[@prisma/client](https://npmjs.com/package/@prisma/client)": [^4.14.1](https://npmjs.com/package/@prisma/client),
[adminjs](https://npmjs.com/package/adminjs): [7.0.0](https://npmjs.com/package/adminjs),
[prisma](https://npmjs.com/package/prisma): [^4.14.1](https://npmjs.com/package/prisma)

**Comment by MichaelTao** [comment]
@Yureien what was your error with 7.0.4? I tried the basic implementation of adminjs with fastify and I got:

FastifyError [Error]: The decorator 'multipartErrors' has already been added!

**Comment by Yureien** [comment]
> @Yureien what was your error with 7.0.4? I tried the basic implementation of adminjs with fastify and I got:
> 
> FastifyError [Error]: The decorator 'multipartErrors' has already been added!

I don't remember exactly. It was some convoluted error and I was in the process of adding Typescript to the code. I just removed both Typescript and reverted AdminJS to 7.0.0 (as they are doing in the example app), and it works now.

I don't think I was getting that error, though. Anyway, you can try using 7.0.0. if that does not work, check the full logs, where that decorator is getting added twice.

I'm using fastify too, btw.

**Comment by Yureien** [comment]
@MichaelTao https://github.com/SoftwareBrothers/adminjs-fastify/issues/14

There are a lot of issues with AdminJS...

**Comment by MichaelTao** [comment]
@Yureien Yeah, I was working on it as I typed it. I don't meet a lot of fastify users. Yeah, I'm going to play around for a little bit longer to see if I can get it up and running or just build from scratch or find alternative solution.

**Comment by vartaller** [comment]
> ```js
> const enumMap = datamodel.enums.reduce((acc, enumItem) => ((acc[enumItem.name] = enumItem), acc), {});
> ```

Hi. I'm trying this code and getting the error:
```
TypeError: Cannot read properties of undefined (reading 'datamodelEnumMap')
    at new Resource (file:///.../node_modules/@adminjs/prisma/src/Resource.ts:30:49)
```

I create Frankenstein, but as best I can:

```
import { Module } from '@nestjs/common';
import { AdminService } from './admin.service';
import { PrismaService } from '../../shared/services/prisma.service';
import { Prisma } from '@prisma/client';

@Module({
  providers: [AdminService],
  imports: [
    import('@adminjs/nestjs').then(async ({ AdminModule }) => {
      const adminService = new AdminService();

      const AdminJSPrisma = await Promise.resolve(import('@adminjs/prisma'));
      const AdminJS = await import('adminjs');
      AdminJS.AdminJS.registerAdapter({
        Resource: AdminJSPrisma.Resource,
        Database: AdminJSPrisma.Database,
      });

      return AdminModule.createAdminAsync({
        useFactory: () => {
          const prisma = new PrismaService();

          const datamodel = Prisma.dmmf.datamodel;
          const models = datamodel.models.reduce(
            (acc, model) => ((acc[model.name] = model), acc),
            {},
          );

          const updatedEnums = datamodel.enums.map((item) => ({
            name: item.name,
            values: item.values,
            dbName: 'strogo',
          }));

          const enumMap = updatedEnums.reduce(
            (acc, enumItem) => ((acc[enumItem.name] = enumItem), acc),
            {},
          );
          console.log(enumMap);
          return {
            adminJsOptions: {
              rootPath: '/admin',
              resources: [
                {
                  resource: {
                    model: models['User'],
                    client: prisma,
                    enumMap: enumMap,
                  },
                  options: {},
                },
              ],
            },
            auth: {
              authenticate: adminService.authenticate.bind(adminService),
              cookieName: 'adminjs',
              cookiePassword: 'secret',
            },
            sessionOptions: {
              resave: true,
              saveUninitialized: true,
              secret: 'secret',
            },
          };
        },
      });
    }),
  ],
})
export class AdminModule {}
```

**Comment by mirashif** [comment]
We made it work by patching the Prisma object itself. Also, you need to install `@prisma/internals` to `getDMMF`. 

```ts
import pkg from '@prisma/internals/dist/index.js'

const { getDMMF } = pkg
const dmmf = await getDMMF({ datamodelPath: './prisma/schema.prisma' })

const prisma = getPrismaClient()
const patched = Object.assign(prisma, {
  _baseDmmf: {
    datamodelEnumMap: dmmf.datamodel.enums,
  },
})

const resources = dmmf.datamodel.models.map(m => ({
  resource: { model: m, client: patched },
  options: {},
}))

const adminOptions: AdminJSOptions = {
  resources,
}
const admin = new AdminJS(adminOptions)
```

**Comment by mirashif** [comment]
We made it work by patching the Prisma object itself. Also, you need to install `@prisma/internals` to `getDMMF`. 

```ts
import prismaInternals from '@prisma/internals/dist/index.js'

const { getDMMF } = prismaInternals
const DMMF = await getDMMF({ datamodelPath: './prisma/schema.prisma' })

const prisma = new PrismaClient()
const patchedClient = Object.assign(prisma, {
  _baseDmmf: {
    datamodelEnumMap: DMMF.datamodel.enums,
  },
})

const resources = DMMF.datamodel.models.map(model => ({
  resource: { model, client: patchedClient },
  options: {},
}))

const adminOptions: AdminJSOptions = {
  resources,
}
const admin = new AdminJS(adminOptions)
```

**Comment by tqvthu-works** [comment]
> `prisma._baseDmmf` was removed with this commit: [prisma/prisma@42087bf](https://github.com/prisma/prisma/commit/42087bfb0148b87d9b927417242b73ce170ad8bd)
> 
> Right now, we are using a really hacky method to get the DMMF. It can be simply obtained using `Prisma.dmmf`.
> 
> Here is my diff on how I patched it (not sure if passing the `enumMaps` through the constructor is the right way or if we can use some other way):
> 
> ```diff
> diff --git a/node_modules/@adminjs/prisma/lib/Resource.js b/node_modules/@adminjs/prisma/lib/Resource.js
> index 7bcc180..7c65c06 100644
> --- a/node_modules/@adminjs/prisma/lib/Resource.js
> +++ b/node_modules/@adminjs/prisma/lib/Resource.js
> @@ -13,10 +13,10 @@ export class Resource extends BaseResource {
>      propertiesObject;
>      constructor(args) {
>          super(args);
> -        const { model, client } = args;
> +        const { model, client, enumMap } = args;
>          this.model = model;
>          this.client = client;
> -        this.enums = this.client._baseDmmf.datamodelEnumMap;
> +        this.enums = enumMap;
>          this.manager = this.client[lowerCase(model.name)];
>          this.propertiesObject = this.prepareProperties();
>      }
> ```
> 
> To get the DMMF properly (and not using internal parameters), we can do it this way:
> 
> ```js
> import { Prisma } from '@prisma/client';
> 
> const prisma = new Prisma.client();
> 
> const datamodel = Prisma.dmmf.datamodel;
> const models = datamodel.models.reduce((acc, model) => ((acc[model.name] = model), acc), {});
> const enumMap = datamodel.enums.reduce((acc, enumItem) => ((acc[enumItem.name] = enumItem), acc), {});
> 
> const resources = [
>   {
>     resource: { model: models['ModelName'], client: prisma, enumMap: enumMap },
>     ...
> ```
> 
> I would create a PR for the `enumMaps` fix if my patch is acceptable, otherwise, please let me know the best way. I would also update the "hacky" way of using `_baseDmmf` to use the official dmmf parameter but I am not sure where all it is getting referenced. Could you please let me know the docs/examples where we are using it?

Can help me resolve this issue?
https://github.com/SoftwareBrothers/adminjs-prisma/issues/40

Thanks
