### ISSUE TITLE
@adminjs/prisma:5.0.0 doesn't work with user-defined output Prisma client

### ISSUE THREAD

**Issue by vsantele** [SoftwareBrothers/adminjs-prisma#42]
Hi,

I tried to update my project with Prisma 5 and @adminjs/prisma 5, but I have a custom path for my output client. 

In @adminjs/prisma:5.0.0, `Resource`'s enums are filled by `getEnums` ([Here](https://github.com/SoftwareBrothers/adminjs-prisma/blob/c22d5c2843c74a00b6fa4c25050da92289971994/src/Resource.ts#L31))
But [`getEnums`](https://github.com/SoftwareBrothers/adminjs-prisma/blob/main/src/utils/get-enums.ts) (and [`getModelByName`](https://github.com/SoftwareBrothers/adminjs-prisma/blob/main/src/utils/get-model-by-name.ts)) use `@prisma/client` to get `datamodel` from `Prisma.dmmf`.

If, in your prisma schema, you define a specific output like this:

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../client"
}
```

The generated code from prisma is inaccessible from `@prisma/client` so you get an error like that:

```log
const dmmf = Prisma.dmmf.datamodel;
                         ^
TypeError: Cannot read properties of undefined (reading 'datamodel')
    at getEnums (node_modules\@adminjs\prisma\src\utils\get-enums.ts:5:28)
```

**Comment by dziraf** [comment]
Not yet finished but something like this might work: https://github.com/SoftwareBrothers/adminjs-prisma/pull/43/files
This isn't the cleanest approach, but I want to make `clientModule` optional so that this fix has backwards compatibility and doesn't require any code changes if 5.0.0 already works for them.
