### ISSUE TITLE
const dmmf = ((prisma as any)._dmmf as DMMFClass)

### ISSUE THREAD

**Issue by alisivandiy** [SoftwareBrothers/adminjs-prisma#7]
How Convert This Code To JavaScript Style :/

what is this !! 
i dont know anything about ts !!!

**Comment by dziraf** [comment]
This is just type casting, in js you can just do:
```
const dmmf = prisma._dmmf;
```

**Comment by alisivandiy** [comment]
> This is just type casting, in js you can just do:
> 
> ```
> const dmmf = prisma._dmmf;
> ```
so with this adapter prisma can conncet to adminjs and send models ?
