### ISSUE TITLE
Unknown arg `mode` in where.name.mode for type StringNullableFilter

### ISSUE THREAD

**Issue by serembon** [SoftwareBrothers/adminjs-prisma#9]
https://github.com/SoftwareBrothers/adminjs-prisma/blob/76e07cbe3115489816282df9557086d8e5df7eab/src/utils/converters.ts#L59

Hello!

Faced with a problem when using the package with Prism and MySQL database. When using search by fields that do not have foreign keys, I get an error:

```bash
Unknown arg `mode` in where.name.mode for type StringNullableFilter. Did you mean `lte`? Available args:
type StringNullableFilter {
  equals?: String | Null
  in?: List<String> | Null
  notIn?: List<String> | Null
  lt?: String
  lte?: String
  gt?: String
  gte?: String
  contains?: String
  startsWith?: String
  endsWith?: String
  not?: String | NestedStringNullableFilter | Null
}
```

The [`convertFilter` ](https://github.com/SoftwareBrothers/adminjs-prisma/blob/76e07cbe3115489816282df9557086d8e5df7eab/src/utils/converters.ts#L59) function contains a strict `mode: 'insensitive'` setting, which causes an error when working with the MySQL

According to [Prisma documentation](https://www.prisma.io/docs/concepts/components/prisma-client/case-sensitivity#mysql-provider):

```text
MySQL uses case-insensitive collation by default. Therefore, filtering with Prisma Client and MySQL is case-insensitive by default.

mode: 'insensitive' property is not required and therefore not available in the generated Prisma Client API.
```

Propose to add some kind of exception for processing requests to MySQL database.

Environment:

- prisma: 3.9.1
- @prisma/client: 3.9.1

**Comment by dziraf** [comment]
@serembon I removed "mode: 'insensitive'" for now so that each provider sticks to it's default behaviour. The fix is included in the latest release.
